#!/usr/bin/env bash

COMMIT_MSG_FILE=$1

# Add a Signed-off-by line if one does not already exist.
SIGN_OFF_BY_TRAILER=$(curl --silent https://penemure.chimera-pumpkinseed.ts.net/me/currently/trailer)
grep -qs "^$SIGN_OFF_BY_TRAILER" "$COMMIT_MSG_FILE" ||
    git interpret-trailers --in-place --trailer "$SIGN_OFF_BY_TRAILER" "$COMMIT_MSG_FILE"

# Detect and abort duplicate Signed-off-by lines.
test "" = "$(grep '^Penemure: ' "$COMMIT_MSG_FILE" |
	 sort | uniq -c | sed -e '/^[ 	]*1[ 	]/d')" || {
	echo >&2 Duplicate Signed-off-by lines.
	exit 1
}
